// app/layout.tsx
import Link from "next/link"; // Still needed if used elsewhere, but not in Header now
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { Analytics } from "@/components/analytics";
import Header from "@/components/NavBar"; // Import the new Header component
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-50 ${inter.className} flex flex-col`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="mx-auto py-10 px-4 flex-grow">
            <Header /> {/* Replace the old header with the new component */}
            <main>{children}</main>
          </div>
          <Analytics />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
